baseurl = "http://eighthbyte.com/"
languageCode = "en-us"
title = "Eighth Byte"
theme = "hugo-theme-casper"
paginate = 5
DisqusShortname = "eighthbyte"
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "Tech Blog"
  cover = "images/cover.jpg"
  author = "Eighth Byte"
  authorlocation = "Tucson, Arizona"
  authorwebsite = "http://eighthbyte.com"
  bio= "Two dudes who love technology"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-65431024-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "eighthbyte"
  twitterName = "8thbyte"
  hideHUGOSupport = false